sonar.organization=umarkhan803
sonar.projectKey=e-commers-for-devops
sonar.projectName=e-commers-for-devops
sonar.sources=frontend/src,backend/src

sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**