apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
data:
  NODE_ENV: "production"
  PORT: "4000"
  API_PREFIX: "/api/v1"
  REDIS_URL: "redis://redis:6379"
  # In-cluster Mongo (your mongo Service name):
  MONGO_URI: "mongodb://mongo:27017/nova_commerce"
  # Or Atlas instead:
  # MONGO_URI: "mongodb+srv://user:pass@cluster.mongodb.net/nova_commerce"
  CORS_ORIGINS: "*"
  JWT_ACCESS_TTL: "15m"
  JWT_REFRESH_TTL: "30d"
  JWT_REFRESH_TTL_SECONDS: "2592000"