apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: umarkhan803/e-commerce-api
          ports:
            - containerPort: 4000
              name: api
          envFrom:
             - configMapRef:
                 name: api-config
             - secretRef:
                 name: api-secret