apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: nova-commerce
  labels:
    app: web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: 905418141604.dkr.ecr.us-east-1.amazonaws.com/nova-commerce/frontend:72a8abbbcfe443b12aabfb6978e1a26b11977a18
          ports:
            - containerPort: 80
              name: web
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          readinessProbe:
            httpGet:
              path: /healthz
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 20
