apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: nova-commerce
  labels:
    app: web
spec:
  type: LoadBalancer
  ports:
    - name: web
      port: 8081
      targetPort: 80
      nodePort: 31000
  selector:
    app: web