apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
  namespace: nova-commerce
data:
  NODE_ENV: "production"
  PORT: "4000"
  API_PREFIX: "/api/v1"
  REDIS_URL: "redis://redis:6379"
  CORS_ORIGINS: "*"
  JWT_ACCESS_TTL: "15m"
  JWT_REFRESH_TTL: "30d"
  JWT_REFRESH_TTL_SECONDS: "2592000"
