
name: CI/CD Pipeline

on:
  push:
    branches: 
        - "main"

  pull_request:
    branches: ["main"]


env:

  NODE_VERSION: "22"



jobs:

    ci:
     name: CI pipeline
     runs-on: ubuntu-latest
     steps:
        # get check out code
      - name: Checkout code 
        uses: actions/checkout@v4
        with:
            fetch-depth: 0
        # setup node
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}            
        # installing frontend dependencies
      - name: building frontend dependencies
        working-directory: frontend
        run: |
         npm ci
         npm run build

        # installing backend dependencies
      - name: Install backend dependencies
        working-directory: backend
        
        run: |
          npm ci
          node --check src/server.js
          node --check src/app.js
          echo "Backend syntax validation passed"

        # scan build using sonar qube
      - name: Sonar Qube Scan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          args: >
            -Dsonar.qualitygate.wait=true
            -Dsonar.qualitygate.timeout=300

          # build backend image
      - name: build backend docker image
        run: |
          docker build \
            -t nove-commerce-backend:${{github.sha}} \
            -f backend/Dockerfile \
            ./backend

     # scan backend docker image using trivy
      - name: scan backend image
        uses: aquasecurity/trivy-action@0.35.0 
        with:
         image-ref: ${{ env.ECR_REGISTRY }}/nova-commerce/backend:${{ github.sha }}
         
         formate: table
         exit-code: 1
         severity: HIGH,CRITICAL
         ignore-unfixed: true
      - name: Push backend image
        run: |
             docker push ${{env.ECR_REGISTRY}}/nova-commerce/backend:${{ github.sha }}

        # build frontend image
      - name: build frontend docker image
        run: |
          docker build \
            -t nove-commerce-frontend:${{github.sha}} \
            -f nginx/Dockerfile \
            .
 
      # scan frontend docker image using trivy
      - name: scan frontend image
        uses: aquasecurity/trivy-action@0.35.0 
        with:
          image-ref: nove-commerce-frontend:${{github.sha}} 
          formate: table
          exit-code: 1
          severity: HIGH,CRITICAL
          ignore-unfixed: true
      - name: Push frontend image
        run: |
               docker push ${{env.ECR_REGISTRY}}/nova-commerce/frontend:${{ github.sha }}